### ISSUE TITLE
Too big sound menu icon in Freya

### ISSUE THREAD

**Issue by bcsopi** [tiliado/nuvola-app-google-play-music#9]
The google play music icon in the sound menu is extremely big, while other services' icons (eg. 8tracks) appear all right. I'm using elementary OS Freya.
![kepernyokep 2016-01-23 14 43 20](https://cloud.githubusercontent.com/assets/11555574/12530441/d17eaf68-c1df-11e5-82d9-9c9805e8b30a.png)

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report this issue. It seems to be an unfortunate coincidence of two bugs:

1. Freya's sound menu is obviously not able to scale down SVG images. You should report this issue to the Freya's bug tracker. (Google Play Music is the only service that provides a hi-res SVG icon instead of a PNG icon, but the other services will follow.)
2. Although Google Play Music provides also PNG icons of various sizes, which could be used by the Freya's sound menu, they are not installed properly with GPM script 5.11 (broken symlinks).

The second issue has been fixed in Google Play Music script 5.12. Could you check it out? I'd recommend to reboot your system after the upgrade of the script as there might be an icon cache in effect.

**Comment by bcsopi** [comment]
Hello!
The issue is fixed in 5.12, looks pretty nice! :)
![kepernyokep 2016-01-25 09 54 04](https://cloud.githubusercontent.com/assets/11555574/12546391/c2b1da26-c349-11e5-8ab1-847ff5cd6403.png)
